### ISSUE TITLE
BlockPlaceEvent Error

### ISSUE THREAD

**Issue by JasonWet** [electronicboy/SilkSpawners#4]
## What steps will reproduce the problem?
Give yourself a blaze spawner or any spawner other than pig
## Expected output
The spawner you have is placed
## What do you see instead?
It places as a pig spawner
## Log file of the issue/error
18.02 13:24:53 [Server] Server thread/ERROR Could not pass event BlockPlaceEvent to SilkSpawners v6.0.0-SNAPSHOT-b${BUILD_NUMBER}
18.02 13:24:53 [Server] INFO org.bukkit.event.EventException: null
18.02 13:24:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:331) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:207) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:481) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1250) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
18.02 13:24:53 [Server] INFO Caused by: net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:Pig
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(SourceFile:38) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftKey.<init>(SourceFile:43) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO at de.dustplanet.silkspawners.compat.v1_15_R1.NMSHandler.setMobNameOfSpawner(NMSHandler.java:146) ~[?:?]
18.02 13:24:53 [Server] INFO at de.dustplanet.util.SilkUtil.setSpawnerEntityID(SilkUtil.java:468) ~[?:?]
18.02 13:24:53 [Server] INFO at de.dustplanet.silkspawners.listeners.SilkSpawnersBlockListener.onBlockPlace(SilkSpawnersBlockListener.java:238) ~[?:?]
18.02 13:24:53 [Server] INFO at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]
18.02 13:24:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
18.02 13:24:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
18.02 13:24:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
18.02 13:24:53 [Server] INFO ... 20 more
## /version output?
Spigot 1.15.2-R0.1-SNAPSHOT

## SilkSpawners version
V6.0.0-SNAPSHOT-b${BUILD_NUMBER}

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Stoniasawsome** [comment]
i had the same problem, i added essentials.spawnerconvert.* and the problem is cured
